from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class MultiAccountAssets: 


	# Image Rule Assets
	# 同心队中心 
	I_TEAM_HOME = RuleImage(roi_front=(932,269,38,38), roi_back=(932,269,38,38), threshold=0.8, method="Template matching", file="./tasks/MultiAccount/resource/team_home.png")
	# 一键寄存 
	I_ONE_STEP_SOURCE = RuleImage(roi_front=(1186,472,72,142), roi_back=(1186,472,72,142), threshold=0.8, method="Template matching", file="./tasks/MultiAccount/resource/one_step_source.png")
	# 集结 
	I_UNION = RuleImage(roi_front=(1095,625,86,59), roi_back=(1095,625,86,59), threshold=0.8, method="Template matching", file="./tasks/MultiAccount/resource/union.png")
	# 御魂副本集结 
	I_YUHUN_UNION = RuleImage(roi_front=(415,317,454,51), roi_back=(415,317,454,51), threshold=0.8, method="Template matching", file="./tasks/MultiAccount/resource/yuhun_union.png")
	# 组队 
	I_MISSION = RuleImage(roi_front=(964,644,67,42), roi_back=(964,644,67,42), threshold=0.8, method="Template matching", file="./tasks/MultiAccount/resource/mission.png")
	# 打开自动 
	I_AUTO = RuleImage(roi_front=(263,649,18,18), roi_back=(100,649,200,18), threshold=0.8, method="Template matching", file="./tasks/MultiAccount/resource/auto.png")
	# 公会信息 
	I_GUILD_INFO = RuleImage(roi_front=(1172,627,65,60), roi_back=(1172,627,65,60), threshold=0.8, method="Template matching", file="./tasks/MultiAccount/resource/guild_info.png")
	# 进入捐赠页面 
	I_DONATE = RuleImage(roi_front=(265,491,36,36), roi_back=(265,491,36,36), threshold=0.8, method="Template matching", file="./tasks/MultiAccount/resource/donate.png")
	# 增加捐赠勾玉数量 
	I_DONATE_ADD = RuleImage(roi_front=(788,290,48,36), roi_back=(788,290,48,36), threshold=0.8, method="Template matching", file="./tasks/MultiAccount/resource/donate_add.png")
	# 确定捐赠 
	I_DONATE_SURE = RuleImage(roi_front=(562,522,157,53), roi_back=(550,510,200,100), threshold=0.8, method="Template matching", file="./tasks/MultiAccount/resource/donate_sure.png")
	# 召唤鬼王 
	I_SUNMMING = RuleImage(roi_front=(1139,587,80,80), roi_back=(1139,587,80,80), threshold=0.8, method="Template matching", file="./tasks/MultiAccount/resource/sunmming.png")
	# 挑战 
	I_CHAR = RuleImage(roi_front=(1139,587,80,80), roi_back=(1139,587,80,80), threshold=0.8, method="Template matching", file="./tasks/MultiAccount/resource/char.png")


